# Generated by Django 6.0.3 on 2026-04-01 15:32

import apps.applications.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('procedure', models.CharField(choices=[('passport_md', 'Passport Application MD'), ('business_reg', 'Individual Entrepreneur Registration')], max_length=30)),
                ('application_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Under Review'), ('PROCESSING', 'Processing'), ('ADDITIONAL_INFO_REQUIRED', 'Additional Info Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='DRAFT', max_length=30)),
                ('form_data', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIReport',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('validation_result', models.JSONField(default=dict)),
                ('extracted_data', models.JSONField(default=dict)),
                ('issues_found', models.JSONField(default=list)),
                ('recommendations', models.TextField(blank=True)),
                ('processing_time_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('ai_model_used', models.CharField(blank=True, max_length=50)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(upload_to=apps.applications.models._document_upload_to)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('file_format', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'DOCX'), ('JPG', 'JPG'), ('PNG', 'PNG')], max_length=10)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user'], name='application_user_id_9457c8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['procedure'], name='application_procedu_258f10_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='application_status_1508e0_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='application_created_c6d08d_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['submitted_at'], name='application_submitt_960277_idx'),
        ),
        migrations.AddIndex(
            model_name='aireport',
            index=models.Index(fields=['created_at'], name='application_created_eb7839_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['application'], name='application_applica_824c17_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['user'], name='application_user_id_0ba6f9_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='application_created_5cacbd_idx'),
        ),
    ]
