# Generated by Django 6.0.3 on 2026-04-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
