# Generated by Django 6.0.3 on 2026-04-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_document_file_format_alter_document_file_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='aireport',
            name='validation_result',
        ),
        migrations.AddField(
            model_name='aireport',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aireport',
            name='decision',
            field=models.CharField(choices=[('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('ERROR', 'Error')], default='REJECT', max_length=10),
        ),
        migrations.AddField(
            model_name='aireport',
            name='prompt_version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
