# Generated by Django 6.0.1 on 2026-02-04 18:09

import apps.photos.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('title', models.CharField(help_text='Entry title (required).', max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Optional description or caption for the entry.', null=True, verbose_name='description')),
                ('user', models.ForeignKey(help_text='The user who owns this entry.', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'entry',
                'verbose_name_plural': 'entries',
                'db_table': 'entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.ImageField(blank=True, help_text='Upload an image file (JPEG, PNG, WebP).', max_length=500, null=True, upload_to=apps.photos.models.photo_upload_path, verbose_name='image file')),
                ('file_size', models.PositiveIntegerField(default=0, editable=False, help_text='File size in bytes.', verbose_name='file size')),
                ('width', models.PositiveIntegerField(default=0, editable=False, help_text='Image width in pixels.', verbose_name='width')),
                ('height', models.PositiveIntegerField(default=0, editable=False, help_text='Image height in pixels.', verbose_name='height')),
                ('entry', models.ForeignKey(help_text='The entry this photo belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='photos.entry', verbose_name='entry')),
                ('user', models.ForeignKey(help_text='Denormalized FK for efficient filtering by user.', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'db_table': 'photos',
                'ordering': ['created_at'],
            },
        ),
    ]
