# Generated by Django 6.0.1 on 2026-02-04 18:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'A user with that email already exists.'}, help_text='Required. Unique email address for authentication.', max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(blank=True, help_text="User's display name.", max_length=150, verbose_name='name')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether the user has verified their email address.', verbose_name='email verified')),
                ('oauth_provider', models.CharField(blank=True, help_text="OAuth provider name (e.g., 'google').", max_length=50, null=True, verbose_name='OAuth provider')),
                ('oauth_id', models.CharField(blank=True, db_index=True, help_text='Unique ID from OAuth provider.', max_length=255, null=True, unique=True, verbose_name='OAuth ID')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='users_email_4b85f2_idx'), models.Index(fields=['oauth_provider', 'oauth_id'], name='users_oauth_p_c54165_idx'), models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'), models.Index(fields=['slug'], name='users_slug_f38108_idx')],
            },
        ),
    ]
